---
- name: IPI-INSTALL Add "{{ myuser }}" user to libvirt group and get ssh key setup
  user: 
    name: "{{ myuser }}"
    groups: libvirt 
    append: yes 
    state: present 
    generate_ssh_key: yes

