- name: Get Release Image Text file
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/{{ version }}/release.txt"
    dest: "{{ dir }}"
    owner: "{{ myuser }}"
    group: "{{ myuser }}"
    mode: '0755'

- name: Register release image value
  shell: |
    cat {{ dir }}/release.txt | grep 'Pull From: quay.io' | awk -F ' ' '{print $3}'
  register: release_image

- debug: msg="{{ release_image.stdout }}"
